#========================================
# Test profile settings (junit tests)
#========================================
Spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///junit-db
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
logging:
  level:
    root: DEBUG

integration:
    party:
      base-url: http://something.com/party
      oauth2:
        token-url: http://something.com/token
        client-id: someClientId
        client-secret: someClientSecret